In [1]:
import pandas as pd
import numpy as np

In [2]:
movies_df   = pd.read_csv("data/clean-movies.csv")
keywords_df = pd.read_csv("data/clean_keywords.csv")
cast_df     = pd.read_csv("data/clean-cast.csv")

In [3]:
first_df = pd.merge(movies_df, keywords_df, on="id")
initial_df = pd.merge(first_df, cast_df, on="id")
initial_df

,adult,budget,genres,id,imdb_id,original_language,popularity,poster_path,release_date,revenue,...,title,video,vote_average,vote_count,clean_genres,keywords,cast,crew,clean_cast,clean_crew
0,False,30000000,"['Animation', 'Comedy', 'Family']",862,tt0114709,en,21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,1995-10-30,373554033.0,...,Toy Story,False,7.7,5415.0,animation comedy family,jealousy toy boy friendship friends rivalry bo...,"['Tom Hanks', 'Tim Allen', 'Don Rickles']",['John Lasseter'],tomhanks timallen donrickles,johnlasseter
1,False,65000000,"['Adventure', 'Fantasy', 'Family']",8844,tt0113497,en,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,1995-12-15,262797249.0,...,Jumanji,False,6.9,2413.0,adventure fantasy family,boardgame disappearance basedonchildren'sbook ...,"['Robin Williams', 'Jonathan Hyde', 'Kirsten D...",['Joe Johnston'],robinwilliams jonathanhyde kirstendunst,joejohnston
2,False,0,"['Romance', 'Comedy']",15602,tt0113228,en,11.712900,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,1995-12-22,0.0,...,Grumpier Old Men,False,6.5,92.0,romance comedy,fishing bestfriend duringcreditsstinger oldmen,"['Walter Matthau', 'Jack Lemmon', 'Ann-Margret']",['Howard Deutch'],waltermatthau jacklemmon ann-margret,howarddeutch
3,False,16000000,"['Comedy', 'Drama', 'Romance']",31357,tt0114885,en,3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,1995-12-22,81452156.0,...,Waiting to Exhale,False,6.1,34.0,comedy drama romance,basedonnovel interracialrelationship singlemot...,"['Whitney Houston', 'Angela Bassett', 'Loretta...",['Forest Whitaker'],whitneyhouston angelabassett lorettadevine,forestwhitaker
4,False,0,['Comedy'],11862,tt0113041,en,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,1995-02-10,76578911.0,...,Father of the Bride Part II,False,5.7,173.0,comedy,baby midlifecrisis confidence aging daughter m...,"['Steve Martin', 'Diane Keaton', 'Martin Short']",['Charles Shyer'],stevemartin dianekeaton martinshort,charlesshyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29718,False,0,"['Crime', 'Drama', 'Thriller']",404604,tt5690142,hi,1.559596,/zZwbntqdfKdVgzH1RoMHa99g0mJ.jpg,2017-07-07,0.0,...,Mom,False,6.6,14.0,crime drama thriller,physicalabuse sexualassault,"['Sridevi Kapoor', 'Sajal Ali', 'Akshaye Khanna']",['Ravi Udyawar'],sridevikapoor sajalali akshayekhanna,raviudyawar
29719,False,0,"['Horror', 'Mystery', 'Thriller']",84419,tt0038621,en,0.222814,/yMnq9mL5uYxbRgwKqyz1cVGCJYJ.jpg,1946-03-29,0.0,...,House of Horrors,False,6.3,8.0,horror mystery thriller,revenge murder serialkiller newyorkcity sculpt...,"['Rondo Hatton', 'Robert Lowery', 'Virginia Gr...",['Jean Yarbrough'],rondohatton robertlowery virginiagrey,jeanyarbrough
29720,False,0,"['Mystery', 'Horror']",390959,tt0265736,en,0.076061,/q75tCM4pFmUzdCg0gqcOQquCaYf.jpg,2000-10-22,0.0,...,Shadow of the Blair Witch,False,7.0,2.0,mystery horror,blairwitch,"['Tony Abatemarco', 'Andre Brooks', 'Mariclare...",['Ben Rock'],tonyabatemarco andrebrooks mariclarecostello,benrock
29721,False,0,['Horror'],289923,tt0252966,en,0.386450,/lXtoHVdej6kS1Dc7KAhw05sMos9.jpg,2000-10-03,0.0,...,The Burkittsville 7,False,7.0,1.0,horror,witch mythology legend serialkiller mockumentary,"['Monty Bane', 'Lucy Butler', 'David Grammer']",['Ben Rock'],montybane lucybutler davidgrammer,benrock
29722,False,0,['Drama'],111109,tt2028550,tl,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,2011-11-17,0.0,...,Century of Birthing,False,9.0,3.0,drama,artist play pinoy,"['Angel Aquino', 'Perry Dizon', 'Hazel Orencio']",['Lav Diaz'],angelaquino perrydizon hazelorencio,lavdiaz

### Selecting the movies with the vote_count of at least 90

In [4]:
initial_df = initial_df[initial_df["vote_count"] > 90].reset_index(drop=True)
initial_df.shape

(6092, 22)

In [5]:
initial_df

,adult,budget,genres,id,imdb_id,original_language,popularity,poster_path,release_date,revenue,...,title,video,vote_average,vote_count,clean_genres,keywords,cast,crew,clean_cast,clean_crew
0,False,30000000,"['Animation', 'Comedy', 'Family']",862,tt0114709,en,21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,1995-10-30,373554033.0,...,Toy Story,False,7.7,5415.0,animation comedy family,jealousy toy boy friendship friends rivalry bo...,"['Tom Hanks', 'Tim Allen', 'Don Rickles']",['John Lasseter'],tomhanks timallen donrickles,johnlasseter
1,False,65000000,"['Adventure', 'Fantasy', 'Family']",8844,tt0113497,en,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,1995-12-15,262797249.0,...,Jumanji,False,6.9,2413.0,adventure fantasy family,boardgame disappearance basedonchildren'sbook ...,"['Robin Williams', 'Jonathan Hyde', 'Kirsten D...",['Joe Johnston'],robinwilliams jonathanhyde kirstendunst,joejohnston
2,False,0,"['Romance', 'Comedy']",15602,tt0113228,en,11.712900,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,1995-12-22,0.0,...,Grumpier Old Men,False,6.5,92.0,romance comedy,fishing bestfriend duringcreditsstinger oldmen,"['Walter Matthau', 'Jack Lemmon', 'Ann-Margret']",['Howard Deutch'],waltermatthau jacklemmon ann-margret,howarddeutch
3,False,0,['Comedy'],11862,tt0113041,en,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,1995-02-10,76578911.0,...,Father of the Bride Part II,False,5.7,173.0,comedy,baby midlifecrisis confidence aging daughter m...,"['Steve Martin', 'Diane Keaton', 'Martin Short']",['Charles Shyer'],stevemartin dianekeaton martinshort,charlesshyer
4,False,60000000,"['Action', 'Crime', 'Drama', 'Thriller']",949,tt0113277,en,17.924927,/zMyfPUelumio3tiDKPffaUpsQTD.jpg,1995-12-15,187436818.0,...,Heat,False,7.7,1886.0,action crime drama thriller,robbery detective bank obsession chase shootin...,"['Al Pacino', 'Robert De Niro', 'Val Kilmer']",['Michael Mann'],alpacino robertdeniro valkilmer,michaelmann
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6087,False,0,"['Drama', 'Crime', 'Thriller']",339692,tt4633690,en,15.786854,/qLmLz2wtyYvmW8Ult3l2ngOnW8v.jpg,2017-07-13,0.0,...,Shot Caller,False,6.9,324.0,drama crime thriller,tattoo prison california desperation shooting ...,"['Nikolaj Coster-Waldau', 'Jon Bernthal', 'Lak...",['Ric Roman Waugh'],nikolajcoster-waldau jonbernthal lakebell,ricromanwaugh
6088,False,0,"['Fantasy', 'Horror', 'Thriller']",440597,tt5322012,en,59.578823,/u0vnocj57vJt5DHoBEqUOD1G4SU.jpg,2017-07-07,0.0,...,Wish Upon,False,5.3,127.0,fantasy horror thriller,magic wishfulfillment,"['Joey King', 'Ryan Phillippe', 'Sherilyn Fenn']",['John R. Leonetti'],joeyking ryanphillippe sherilynfenn,johnr.leonetti
6089,False,0,"['TV Movie', 'Family', 'Action', 'Comedy', 'Mu...",417320,tt5117876,en,15.842073,/7TLywOVzWwU1GMyqdjUiSVzBiyc.jpg,2017-07-21,0.0,...,Descendants 2,False,7.5,171.0,tvmovie family action comedy music adventure,fairytale villain musical teenmovie teenager,"['Dove Cameron', 'Sofia Carson', 'Cameron Boyce']",['Kenny Ortega'],dovecameron sofiacarson cameronboyce,kennyortega
6090,False,25868826,['Comedy'],248705,tt2441982,fr,7.294920,/2tR5dfWONNPCjW3Th2RFk2DuLsY.jpg,2016-03-23,0.0,...,The Visitors: Bastille Day,False,4.0,167.0,comedy,nazis castle timetravel robespierre,"['Jean Reno', 'Christian Clavier', 'Franck Dub...",['Jean-Marie Poiré'],jeanreno christianclavier franckdubosc,jean-mariepoiré
6091,False,0,['Comedy'],14008,tt0294425,en,4.392389,/9sQVYo7B9cSexWXoQVzFFijCbD2.jpg,2002-03-07,0.0,...,Cadet Kelly,False,5.2,145.0,comedy,militaryschool,"['Hilary Duff', 'Christy Carlson Romano', 'Gar...",['Larry Shaw'],hilaryduff christycarlsonromano garycole,larryshaw

# Selecting the features required for Content-Based
Columns required for content-based filtering:  
* title
* genres
* cast
* crew
* keywords

In [6]:
initial_df = initial_df[["id", "title", "genres", "cast", "crew", "keywords", "poster_path", "vote_average"]]
initial_df

,id,title,genres,cast,crew,keywords,poster_path,vote_average
0,862,Toy Story,"['Animation', 'Comedy', 'Family']","['Tom Hanks', 'Tim Allen', 'Don Rickles']",['John Lasseter'],jealousy toy boy friendship friends rivalry bo...,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,7.7
1,8844,Jumanji,"['Adventure', 'Fantasy', 'Family']","['Robin Williams', 'Jonathan Hyde', 'Kirsten D...",['Joe Johnston'],boardgame disappearance basedonchildren'sbook ...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,6.9
2,15602,Grumpier Old Men,"['Romance', 'Comedy']","['Walter Matthau', 'Jack Lemmon', 'Ann-Margret']",['Howard Deutch'],fishing bestfriend duringcreditsstinger oldmen,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,6.5
3,11862,Father of the Bride Part II,['Comedy'],"['Steve Martin', 'Diane Keaton', 'Martin Short']",['Charles Shyer'],baby midlifecrisis confidence aging daughter m...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,5.7
4,949,Heat,"['Action', 'Crime', 'Drama', 'Thriller']","['Al Pacino', 'Robert De Niro', 'Val Kilmer']",['Michael Mann'],robbery detective bank obsession chase shootin...,/zMyfPUelumio3tiDKPffaUpsQTD.jpg,7.7
...,...,...,...,...,...,...,...,...
6087,339692,Shot Caller,"['Drama', 'Crime', 'Thriller']","['Nikolaj Coster-Waldau', 'Jon Bernthal', 'Lak...",['Ric Roman Waugh'],tattoo prison california desperation shooting ...,/qLmLz2wtyYvmW8Ult3l2ngOnW8v.jpg,6.9
6088,440597,Wish Upon,"['Fantasy', 'Horror', 'Thriller']","['Joey King', 'Ryan Phillippe', 'Sherilyn Fenn']",['John R. Leonetti'],magic wishfulfillment,/u0vnocj57vJt5DHoBEqUOD1G4SU.jpg,5.3
6089,417320,Descendants 2,"['TV Movie', 'Family', 'Action', 'Comedy', 'Mu...","['Dove Cameron', 'Sofia Carson', 'Cameron Boyce']",['Kenny Ortega'],fairytale villain musical teenmovie teenager,/7TLywOVzWwU1GMyqdjUiSVzBiyc.jpg,7.5
6090,248705,The Visitors: Bastille Day,['Comedy'],"['Jean Reno', 'Christian Clavier', 'Franck Dub...",['Jean-Marie Poiré'],nazis castle timetravel robespierre,/2tR5dfWONNPCjW3Th2RFk2DuLsY.jpg,4.0
6091,14008,Cadet Kelly,['Comedy'],"['Hilary Duff', 'Christy Carlson Romano', 'Gar...",['Larry Shaw'],militaryschool,/9sQVYo7B9cSexWXoQVzFFijCbD2.jpg,5.2

# 1. Text Preprocessing

- 1. Removing special characters and digits except _  
- 2. Converting to lowercase 
- 3. Tokenization (Word-level) 
> 3.1. TextBlob- Correcting the spellings 
- 4. Removing stopwords
- 5. stemming/lemmatization

In [7]:
initial_df["tags"] = initial_df["genres"] + " " + initial_df["cast"] + " " + initial_df["crew"] + " " + initial_df["keywords"]
initial_df["tags"] = initial_df["tags"].apply(lambda x: x.lower())

initial_df

/var/folders/nb/9rv0k2zs65xfgzvd88cpv_8m0000gp/T/ipykernel_3713/1224272392.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  initial_df["tags"] = initial_df["genres"] + " " + initial_df["cast"] + " " + initial_df["crew"] + " " + initial_df["keywords"]
/var/folders/nb/9rv0k2zs65xfgzvd88cpv_8m0000gp/T/ipykernel_3713/1224272392.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  initial_df["tags"] = initial_df["tags"].apply(lambda x: x.lower())

,id,title,genres,cast,crew,keywords,poster_path,vote_average,tags
0,862,Toy Story,"['Animation', 'Comedy', 'Family']","['Tom Hanks', 'Tim Allen', 'Don Rickles']",['John Lasseter'],jealousy toy boy friendship friends rivalry bo...,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,7.7,"['animation', 'comedy', 'family'] ['tom hanks'..."
1,8844,Jumanji,"['Adventure', 'Fantasy', 'Family']","['Robin Williams', 'Jonathan Hyde', 'Kirsten D...",['Joe Johnston'],boardgame disappearance basedonchildren'sbook ...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,6.9,"['adventure', 'fantasy', 'family'] ['robin wil..."
2,15602,Grumpier Old Men,"['Romance', 'Comedy']","['Walter Matthau', 'Jack Lemmon', 'Ann-Margret']",['Howard Deutch'],fishing bestfriend duringcreditsstinger oldmen,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,6.5,"['romance', 'comedy'] ['walter matthau', 'jack..."
3,11862,Father of the Bride Part II,['Comedy'],"['Steve Martin', 'Diane Keaton', 'Martin Short']",['Charles Shyer'],baby midlifecrisis confidence aging daughter m...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,5.7,"['comedy'] ['steve martin', 'diane keaton', 'm..."
4,949,Heat,"['Action', 'Crime', 'Drama', 'Thriller']","['Al Pacino', 'Robert De Niro', 'Val Kilmer']",['Michael Mann'],robbery detective bank obsession chase shootin...,/zMyfPUelumio3tiDKPffaUpsQTD.jpg,7.7,"['action', 'crime', 'drama', 'thriller'] ['al ..."
...,...,...,...,...,...,...,...,...,...
6087,339692,Shot Caller,"['Drama', 'Crime', 'Thriller']","['Nikolaj Coster-Waldau', 'Jon Bernthal', 'Lak...",['Ric Roman Waugh'],tattoo prison california desperation shooting ...,/qLmLz2wtyYvmW8Ult3l2ngOnW8v.jpg,6.9,"['drama', 'crime', 'thriller'] ['nikolaj coste..."
6088,440597,Wish Upon,"['Fantasy', 'Horror', 'Thriller']","['Joey King', 'Ryan Phillippe', 'Sherilyn Fenn']",['John R. Leonetti'],magic wishfulfillment,/u0vnocj57vJt5DHoBEqUOD1G4SU.jpg,5.3,"['fantasy', 'horror', 'thriller'] ['joey king'..."
6089,417320,Descendants 2,"['TV Movie', 'Family', 'Action', 'Comedy', 'Mu...","['Dove Cameron', 'Sofia Carson', 'Cameron Boyce']",['Kenny Ortega'],fairytale villain musical teenmovie teenager,/7TLywOVzWwU1GMyqdjUiSVzBiyc.jpg,7.5,"['tv movie', 'family', 'action', 'comedy', 'mu..."
6090,248705,The Visitors: Bastille Day,['Comedy'],"['Jean Reno', 'Christian Clavier', 'Franck Dub...",['Jean-Marie Poiré'],nazis castle timetravel robespierre,/2tR5dfWONNPCjW3Th2RFk2DuLsY.jpg,4.0,"['comedy'] ['jean reno', 'christian clavier', ..."
6091,14008,Cadet Kelly,['Comedy'],"['Hilary Duff', 'Christy Carlson Romano', 'Gar...",['Larry Shaw'],militaryschool,/9sQVYo7B9cSexWXoQVzFFijCbD2.jpg,5.2,"['comedy'] ['hilary duff', 'christy carlson ro..."

In [8]:
df = initial_df[["id", "title", "tags", "poster_path", "genres", "vote_average"]]
df

,id,title,tags,poster_path,genres,vote_average
0,862,Toy Story,"['animation', 'comedy', 'family'] ['tom hanks'...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"['Animation', 'Comedy', 'Family']",7.7
1,8844,Jumanji,"['adventure', 'fantasy', 'family'] ['robin wil...",/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"['Adventure', 'Fantasy', 'Family']",6.9
2,15602,Grumpier Old Men,"['romance', 'comedy'] ['walter matthau', 'jack...",/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"['Romance', 'Comedy']",6.5
3,11862,Father of the Bride Part II,"['comedy'] ['steve martin', 'diane keaton', 'm...",/e64sOI48hQXyru7naBFyssKFxVd.jpg,['Comedy'],5.7
4,949,Heat,"['action', 'crime', 'drama', 'thriller'] ['al ...",/zMyfPUelumio3tiDKPffaUpsQTD.jpg,"['Action', 'Crime', 'Drama', 'Thriller']",7.7
...,...,...,...,...,...,...
6087,339692,Shot Caller,"['drama', 'crime', 'thriller'] ['nikolaj coste...",/qLmLz2wtyYvmW8Ult3l2ngOnW8v.jpg,"['Drama', 'Crime', 'Thriller']",6.9
6088,440597,Wish Upon,"['fantasy', 'horror', 'thriller'] ['joey king'...",/u0vnocj57vJt5DHoBEqUOD1G4SU.jpg,"['Fantasy', 'Horror', 'Thriller']",5.3
6089,417320,Descendants 2,"['tv movie', 'family', 'action', 'comedy', 'mu...",/7TLywOVzWwU1GMyqdjUiSVzBiyc.jpg,"['TV Movie', 'Family', 'Action', 'Comedy', 'Mu...",7.5
6090,248705,The Visitors: Bastille Day,"['comedy'] ['jean reno', 'christian clavier', ...",/2tR5dfWONNPCjW3Th2RFk2DuLsY.jpg,['Comedy'],4.0
6091,14008,Cadet Kelly,"['comedy'] ['hilary duff', 'christy carlson ro...",/9sQVYo7B9cSexWXoQVzFFijCbD2.jpg,['Comedy'],5.2

In [9]:
from ast import literal_eval
df["genres"] = df["genres"].apply(lambda x: literal_eval(x))

df

/var/folders/nb/9rv0k2zs65xfgzvd88cpv_8m0000gp/T/ipykernel_3713/3391737180.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["genres"] = df["genres"].apply(lambda x: literal_eval(x))

,id,title,tags,poster_path,genres,vote_average
0,862,Toy Story,"['animation', 'comedy', 'family'] ['tom hanks'...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[Animation, Comedy, Family]",7.7
1,8844,Jumanji,"['adventure', 'fantasy', 'family'] ['robin wil...",/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[Adventure, Fantasy, Family]",6.9
2,15602,Grumpier Old Men,"['romance', 'comedy'] ['walter matthau', 'jack...",/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[Romance, Comedy]",6.5
3,11862,Father of the Bride Part II,"['comedy'] ['steve martin', 'diane keaton', 'm...",/e64sOI48hQXyru7naBFyssKFxVd.jpg,[Comedy],5.7
4,949,Heat,"['action', 'crime', 'drama', 'thriller'] ['al ...",/zMyfPUelumio3tiDKPffaUpsQTD.jpg,"[Action, Crime, Drama, Thriller]",7.7
...,...,...,...,...,...,...
6087,339692,Shot Caller,"['drama', 'crime', 'thriller'] ['nikolaj coste...",/qLmLz2wtyYvmW8Ult3l2ngOnW8v.jpg,"[Drama, Crime, Thriller]",6.9
6088,440597,Wish Upon,"['fantasy', 'horror', 'thriller'] ['joey king'...",/u0vnocj57vJt5DHoBEqUOD1G4SU.jpg,"[Fantasy, Horror, Thriller]",5.3
6089,417320,Descendants 2,"['tv movie', 'family', 'action', 'comedy', 'mu...",/7TLywOVzWwU1GMyqdjUiSVzBiyc.jpg,"[TV Movie, Family, Action, Comedy, Music, Adve...",7.5
6090,248705,The Visitors: Bastille Day,"['comedy'] ['jean reno', 'christian clavier', ...",/2tR5dfWONNPCjW3Th2RFk2DuLsY.jpg,[Comedy],4.0
6091,14008,Cadet Kelly,"['comedy'] ['hilary duff', 'christy carlson ro...",/9sQVYo7B9cSexWXoQVzFFijCbD2.jpg,[Comedy],5.2

## Unique Genres

In [10]:
def get_unique(list_of_lists):

    from ast import literal_eval
    
    elements = []
    for list1 in list_of_lists:
        for element in list1:
            elements.append(element)
    return list(set(elements))

unique_genres = get_unique(df["genres"])
unique_genres # All the genres that a user can select

['Comedy',
 'Science Fiction',
 'Crime',
 'Western',
 'War',
 'Action',
 'Family',
 'Horror',
 'History',
 'Animation',
 'Mystery',
 'TV Movie',
 'Documentary',
 'Fantasy',
 'Drama',
 'Romance',
 'Thriller',
 'Adventure',
 'Music']

# Saving CSV file for Web Application

In [11]:
df.to_csv("data/content-based-dataset.csv")

# Understanding the need for the column "tags"

- We recommend movies to the user based on the similarity of the user-inputed-movies and the "tags" column.

### It looks something like this-

1. Prompt the users with something like this- "Please enter a movie that you like."  
> Movie: (user_selected) 

2. We search the inputed movies' 
> 1. genre,  
> 2. cast,  
> 3. crew,
> 4. keywords. 

3. We then combine all the values into one single tag. Let's call it **query_tag**
4. Then, we need to **find 5 movies which have the most similarity** to the **query_tag**
5. Now, the question is, **how to calculate that similarity**?

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000) # Selecting top 5k most occuring words

In [13]:
# cv.fit_transform(df["tags"]) ---> this will return us a sparse matrix because most values are 0.
# So, scipy defaults this as a sparse matrix.
# So, we need to convert it into an array.

vectors = cv.fit_transform(df["tags"]).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [14]:
vectors.shape

(6092, 5000)

In [15]:
vectors[0] # There are 5000 dimensions. That's why it's not showing us all of them.

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
len(cv.get_feature_names_out())

5000

In [17]:
print(cv.get_feature_names_out()[45])

advertising

# Calculating the distance to find the similarity

### Euclidean Distance is not a good measure to calculate the distance between two points when there are a lot of datapoints.
### A better measure is - COSINE DISTANCE that calculates the angle between two vectors
# Cosine Distance is the angle between two vectors
## The lesser the angle, the more similar two vectors are

* We have a formula we can import to calculate the cosine distance between two vectors.

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
cos_similarity = cosine_similarity(vectors)

In [20]:
cos_similarity

array([[1.        , 0.06262243, 0.070014  , ..., 0.10846523, 0.06482037,
        0.08574929],
       [0.06262243, 1.        , 0.        , ..., 0.11547005, 0.        ,
        0.        ],
       [0.070014  , 0.        , 1.        , ..., 0.06454972, 0.07715167,
        0.10206207],
       ...,
       [0.10846523, 0.11547005, 0.06454972, ..., 1.        , 0.05976143,
        0.07905694],
       [0.06482037, 0.        , 0.07715167, ..., 0.05976143, 1.        ,
        0.09449112],
       [0.08574929, 0.        , 0.10206207, ..., 0.07905694, 0.09449112,
        1.        ]])

In [21]:
cos_similarity.shape

(6092, 6092)

In [22]:
cos_similarity[0] # This represents the similarity between this specific movie and ALL THE OTHER MOVIES

array([1.        , 0.06262243, 0.070014  , ..., 0.10846523, 0.06482037,
       0.08574929])

In [23]:
cos_similarity[1]

array([0.06262243, 1.        , 0.        , ..., 0.11547005, 0.        ,
       0.        ])

In [24]:
cos_similarity[2]

array([0.070014  , 0.        , 1.        , ..., 0.06454972, 0.07715167,
       0.10206207])

In [25]:
# observe the 1's in the above three outputs.
# the distance between movie_1 and movie_1 is 1.
# the distance between movie_2 and movie_2 is 1.
# the distance between movie_3 and movie_3 is 1.

## The closer the value is to 1, the more similar a movie is

# RECOMMENDING MOVIES based on Cosine Similarity

In [26]:
df["title"].head(20)

0                          Toy Story
1                            Jumanji
2                   Grumpier Old Men
3        Father of the Bride Part II
4                               Heat
5                            Sabrina
6                       Sudden Death
7                          GoldenEye
8             The American President
9        Dracula: Dead and Loving It
10                             Balto
11                  Cutthroat Island
12                            Casino
13             Sense and Sensibility
14                        Four Rooms
15    Ace Ventura: When Nature Calls
16                       Money Train
17                        Get Shorty
18                           Copycat
19                         Assassins
Name: title, dtype: object

In [27]:
def recommend(movie, user_genre="", min_rating = 1):
    movie_index = df[df["title"] == movie].index[0]
    similarities = cos_similarity[movie_index]
    
    # in order to not lose the movie_index, we can use enumerate function and typecast it to list to make it readable
    recommendations_indexes = sorted(list(enumerate(similarities)), reverse=True, key=lambda x:x[1])
    # In the above code, the "key=lambda x:x[1]" is used to specifically sort the movies based on the similarities and not based on the index values.
    
    recommendations   = []
    similarity_scores = []
    vote_averages   = []
    genres = []
    for tuples in recommendations_indexes:
        
        recommendations.append(df["title"][tuples[0]])
        similarity_scores.append(round(tuples[1], 2))
        vote_averages.append(df["vote_average"][tuples[0]])
        genres.append(df["genres"][tuples[0]])
        
    recommended_df = pd.DataFrame({"Recommendations": recommendations, 
                                   "Similarity": similarity_scores,
                                   "Genres": genres,
                                   "Rating": vote_averages})
    try:
        
        if not user_genre:
            
            final_recommendation = recommended_df[recommended_df["Rating"] >= min_rating]
            
            if len(final_recommendation) > 11:
                return final_recommendation[1:11]
            else:
                return final_recommendation[1:]
            
        else:
            # Recommending movies based on genre.
            matching_genres = recommended_df[recommended_df["Genres"].apply(lambda x: user_genre in x)].index
            filtered_recommendation = recommended_df.iloc[matching_genres]

            final_recommendation = filtered_recommendation[filtered_recommendation["Rating"] >= min_rating]

            if len(final_recommendation) > 11:
                return final_recommendation[1:11]
            else:
                return final_recommendation[1:]
    except:
        message = "Sorry. No movies exist with the filters selected. Try changing the filters again."
        return message

In [28]:
recommend("Toy Story", min_rating = 7)

,Recommendations,Similarity,Genres,Rating
1,Toy Story 2,0.60,"[Animation, Comedy, Family]",7.3
2,Toy Story 3,0.54,"[Animation, Family, Comedy]",7.6
4,Toy Story of Terror!,0.49,"[Animation, Comedy, Family]",7.3
7,It's Such a Beautiful Day,0.32,"[Fantasy, Animation, Comedy, Drama]",7.8
10,Saving Mr. Banks,0.31,"[Comedy, Drama, History]",7.3
21,The Odd Couple,0.29,[Comedy],7.5
22,"Monsters, Inc.",0.29,"[Animation, Comedy, Family]",7.5
35,Spirit: Stallion of the Cimarron,0.27,"[Western, Animation, Adventure, Comedy, Family]",7.4
37,Aladdin,0.27,"[Animation, Family, Comedy, Adventure, Fantasy...",7.4
38,Anastasia,0.27,"[Animation, Family]",7.4

In [29]:
recommend("Toy Story", user_genre="Drama", min_rating = 7)

,Recommendations,Similarity,Genres,Rating
10,Saving Mr. Banks,0.31,"[Comedy, Drama, History]",7.3
60,Inside Out,0.25,"[Drama, Comedy, Animation, Family]",7.9
75,Our Little Sister,0.24,"[Drama, Comedy]",7.1
83,Hachi: A Dog's Tale,0.24,"[Drama, Family]",7.7
85,Ernest & Celestine,0.24,"[Animation, Comedy, Drama, Family]",7.6
117,Children of Heaven,0.22,"[Drama, Comedy, Family]",7.8
123,The Terminal,0.21,"[Comedy, Drama]",7.1
133,The Triplets of Belleville,0.21,"[Adventure, Animation, Comedy, Drama]",7.3
135,The Station Agent,0.21,"[Drama, Comedy]",7.4
143,Feast,0.21,"[Animation, Comedy, Drama, Family]",8.0

In [30]:
recommend("Jumanji")

,Recommendations,Similarity,Genres,Rating
1,Tinker Bell and the Lost Treasure,0.36,"[Animation, Family, Adventure, Fantasy]",6.4
2,Aladdin and the King of Thieves,0.34,"[Adventure, Animation, Family]",6.1
3,Hook,0.33,"[Adventure, Fantasy, Comedy, Family]",6.7
4,Ronal the Barbarian,0.32,"[Animation, Adventure, Fantasy]",6.2
5,Small Soldiers,0.31,"[Comedy, Adventure, Fantasy, Science Fiction, ...",6.2
6,Where the Wild Things Are,0.30,"[Family, Fantasy]",6.4
7,Return to Oz,0.29,"[Adventure, Family, Fantasy]",6.6
8,Sapphire Blue,0.29,"[Adventure, Family, Fantasy]",6.9
9,The Pagemaster,0.29,"[Fantasy, Science Fiction, Family, Animation]",6.2
10,Arthur and the Invisibles,0.29,"[Adventure, Fantasy, Animation, Family]",6.0